[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[lint]
lint = true
exclude_lints = [
    "unaliased-plain-import",
    "unwrapped-modifier-logic",
    "asm-keccak256",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
